# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tix3Dev's Blog
email: yves.vollmeier.code@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog about all kinds of nerdy stuff :D
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tix3dev.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
repository: Tix3Dev/tix3dev.github.io 
github: Tix3Dev

header_image: assets/profile.gif

google_analytics:
comments: true
disqus: purelog-jekyll

author: Yves Vollmeier
author_bio: >-
  Hey there! 👋 My name is Yves aka Tix3Dev.<br/>
  I am a 16 year old computer science/engineering enthusiast from Switzerland.<br/>
  Currently, I am really passionate about OSDev.<br/>
  My interests aren't just limited to programming but rather STEM as a whole.<br/>
author_pic: /assets/avatar.png

paginate: 4
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Yves Vollmeier
      avatar: assets/profile-sm.png
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ""
      type: journals
    values:
      layout: journal-entry
      content-type: journals

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title
  notes:
    output: true
    permalink: /notes/:title
  journals:
    output: true
    permalink: /journals/:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
